---
# tasks file for add_ios_user
- name: create a new user
  ios_user:
    name: emergent
    configured_password: "emergent-42-foo!"
    password_type: secret
    update_password: always
    privilege: 15
    state: present