---
# tasks file for add_ios_user
- name: create a new user
  ios_user:
    name: emergent
    nopassword: True
    sshkey: "{{ ec2_name_prefix }}-key"
    privilege: 15
    state: present
  no_log: True