---
# tasks file for add_ios_user
- name: create a new user
  ios_user:
    name: emergent
    nopassword: True
    sshkey: "{{ network_rsa_key }}"
    privilege: 15
    state: present
    no_log: True
  #no_log: True